import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../layout";
import Hero from "../sections/Hero";
import Products from "../sections/Products";
import Promotion from "../sections/Promotion";
import NewProducts from "../sections/NewProducts";
import Services from "../sections/Services";
import NewArrivial from "../sections/NewArrivial";
import Testimonial from "../sections/Testimonial";
import News from "../sections/News";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plant Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Products />
        <Promotion />
        <NewProducts />
        <Services />
        <NewArrivial />
        <Testimonial />
        <News />
      </Layout>
    </div>
  );
};

export default Home;
